/* exath-engine C API, auto-generated by cbindgen, do not edit manually */

#ifndef EXATH_ENGINE_H
#define EXATH_ENGINE_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Angle mode constants for use from C.
 */
typedef enum ExathAngleMode {
    Deg = 0,
    Rad = 1,
    Grad = 2,
} ExathAngleMode;

/**
 * Opaque session handle.  Allocate with exath_session_new(), free with exath_session_free().
 */
typedef struct ExathSession ExathSession;

/**
 * Result returned from evaluation functions.
 * If is_error == 0: re and im contain the result (im == 0 for real results).
 * If is_error == 1: error_msg contains a null-terminated error string.
 *   Free it with exath_free_string() after use.
 */
typedef struct ExathResult {
    double re;
    double im;
    /**
     * 1 if the result is complex (im != 0), else 0.
     */
    int32_t is_complex;
    int32_t is_error;
    char *error_msg;
} ExathResult;

/**
 * Result of exath_session_eval_line.
 * If is_error == 1: error_msg holds the message (free with exath_free_string).
 * Else if is_expression == 1: expression holds a symbolic expression string
 *   (free with exath_free_string); re/im are 0.
 * Else: re/im hold the numeric value and expression is NULL.
 */
typedef struct ExathLineResult {
    int32_t is_expression;
    char *expression;
    double re;
    double im;
    /**
     * 1 if the numeric value is complex (im != 0), else 0.
     */
    int32_t is_complex;
    int32_t is_error;
    char *error_msg;
} ExathLineResult;

/**
 * Free an error_msg string returned by any exath function.
 */
void exath_free_string(char *ptr);

/**
 * Evaluate an expression string.
 * Returns ExathResult, free error_msg with exath_free_string() if is_error == 1.
 */
struct ExathResult exath_evaluate(const char *expr, enum ExathAngleMode angle_mode);

/**
 * Returns 1 if the expression parses correctly, 0 otherwise.
 */
int32_t exath_is_valid(const char *expr);

/**
 * Returns a null-terminated, comma-separated list of supported function names.
 * Free the result with exath_free_string().
 */
char *exath_supported_functions(void);

/**
 * Create a new session.
 */
struct ExathSession *exath_session_new(enum ExathAngleMode angle_mode);

/**
 * Free a session created with exath_session_new().
 */
void exath_session_free(struct ExathSession *session);

/**
 * Evaluate one line in a session (may be `var = expr` or a plain expression).
 * Returns ExathResult, free error_msg with exath_free_string() if is_error == 1.
 */
struct ExathResult exath_session_eval(struct ExathSession *session, const char *line);

/**
 * Evaluate one line, understanding every DSL form, symbolic (diff, simplify,
 * factor, solve, integral, …), linear algebra (det, inv, eigenvalues, …) and
 * numeric forms (sum, product, deriv). See ExathLineResult for the result
 * convention. This is the single gateway for all operations.
 */
struct ExathLineResult exath_session_eval_line(struct ExathSession *session, const char *line);

/**
 * Set a variable in the session.  im = 0.0 for real values.
 */
void exath_session_set_var(struct ExathSession *session, const char *name, double re, double im);

/**
 * Remove a variable from the session.
 */
void exath_session_remove_var(struct ExathSession *session, const char *name);

/**
 * Clear all variables in the session.
 */
void exath_session_clear_vars(struct ExathSession *session);

/**
 * Remove a user-defined function from the session.
 */
void exath_session_remove_fn(struct ExathSession *session, const char *name);

/**
 * Returns a null-terminated, comma-separated list of user-defined function names.
 * Free the result with exath_free_string().
 */
char *exath_session_fn_names(struct ExathSession *session);

/**
 * Returns a null-terminated, comma-separated list of variable names.
 * Free the result with exath_free_string().
 */
char *exath_session_var_names(struct ExathSession *session);

#endif  /* EXATH_ENGINE_H */
