/* exath-engine C API — auto-generated by cbindgen, do not edit manually */

#ifndef EXATH_ENGINE_H
#define EXATH_ENGINE_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Angle mode constants for use from C.
 */
typedef enum ExathAngleMode {
    Deg = 0,
    Rad = 1,
    Grad = 2,
} ExathAngleMode;

/**
 * Opaque session handle.  Allocate with exath_session_new(), free with exath_session_free().
 */
typedef struct ExathSession ExathSession;

/**
 * Result returned from evaluation functions.
 * If is_error == 0: re and im contain the result (im == 0 for real results).
 * If is_error == 1: error_msg contains a null-terminated error string.
 *   Free it with exath_free_string() after use.
 */
typedef struct ExathResult {
    double re;
    double im;
    int32_t is_error;
    char *error_msg;
} ExathResult;

/**
 * Free an error_msg string returned by any exath function.
 */
void exath_free_string(char *s);

/**
 * Evaluate an expression string.
 * Returns ExathResult — free error_msg with exath_free_string() if is_error == 1.
 */
struct ExathResult exath_evaluate(const char *expr, enum ExathAngleMode angle_mode);

/**
 * Returns 1 if the expression parses correctly, 0 otherwise.
 */
int32_t exath_is_valid(const char *expr);

/**
 * Returns a null-terminated, comma-separated list of supported function names.
 * Free the result with exath_free_string().
 */
char *exath_supported_functions(void);

/**
 * Numerically differentiate expr w.r.t. var at x.
 */
struct ExathResult exath_deriv(const char *expr,
                               const char *var,
                               double x,
                               enum ExathAngleMode angle_mode);

/**
 * Numerically integrate expr w.r.t. var from a to b.
 */
struct ExathResult exath_integrate(const char *expr,
                                   const char *var,
                                   double a,
                                   double b,
                                   enum ExathAngleMode angle_mode);

/**
 * Compute Σ expr for var = from to to (inclusive).
 */
struct ExathResult exath_sum(const char *expr,
                             const char *var,
                             int64_t from,
                             int64_t to,
                             enum ExathAngleMode angle_mode);

/**
 * Compute Π expr for var = from to to (inclusive).
 */
struct ExathResult exath_prod(const char *expr,
                              const char *var,
                              int64_t from,
                              int64_t to,
                              enum ExathAngleMode angle_mode);

/**
 * Create a new session.
 */
struct ExathSession *exath_session_new(enum ExathAngleMode angle_mode);

/**
 * Free a session created with exath_session_new().
 */
void exath_session_free(struct ExathSession *session);

/**
 * Evaluate one line in a session (may be `var = expr` or a plain expression).
 * Returns ExathResult — free error_msg with exath_free_string() if is_error == 1.
 */
struct ExathResult exath_session_eval(struct ExathSession *session, const char *line);

/**
 * Set a variable in the session.  im = 0.0 for real values.
 */
void exath_session_set_var(struct ExathSession *session, const char *name, double re, double im);

/**
 * Remove a variable from the session.
 */
void exath_session_remove_var(struct ExathSession *session, const char *name);

/**
 * Clear all variables in the session.
 */
void exath_session_clear_vars(struct ExathSession *session);

#endif  /* EXATH_ENGINE_H */
